const filters = ["Today", "Next 7days"];
const segments = ["Forecast", "Air Quality"];

export {
    filters,
    segments
}

export const countryTimeZones: Record<string, string> = {
  // --- ORIGINAL ENTRIES & ALIASES ---
  nigeria: "Africa/Lagos",
  ghana: "Africa/Accra",
  kenya: "Africa/Nairobi",
  south_africa: "Africa/Johannesburg",
  united_kingdom: "Europe/London",
  uk: "Europe/London",
  usa: "America/New_York",
  united_states: "America/New_York",
  canada: "America/Toronto",
  india: "Asia/Kolkata",
  china: "Asia/Shanghai",
  japan: "Asia/Tokyo",
  australia: "Australia/Sydney",

  // --- AFRICA ---
  algeria: "Africa/Algiers",
  angola: "Africa/Luanda",
  benin: "Africa/Porto-Novo",
  botswana: "Africa/Gaborone",
  burkina_faso: "Africa/Ouagadougou",
  burundi: "Africa/Bujumbura",
  cameroon: "Africa/Douala",
  cape_verde: "Atlantic/Cape_Verde",
  central_african_republic: "Africa/Bangui",
  chad: "Africa/Ndjamena",
  comoros: "Indian/Comoro",
  congo_brazzaville: "Africa/Brazzaville",
  congo_kinshasa: "Africa/Kinshasa",
  djibouti: "Africa/Djibouti",
  egypt: "Africa/Cairo",
  equatorial_guinea: "Africa/Malabo",
  eritrea: "Africa/Asmara",
  eswatini: "Africa/Mbabane",
  swaziland: "Africa/Mbabane",
  ethiopia: "Africa/Addis_Ababa",
  gabon: "Africa/Libreville",
  gambia: "Africa/Banjul",
  guinea: "Africa/Conakry",
  guinea_bissau: "Africa/Bissau",
  ivory_coast: "Africa/Abidjan",
  cote_divoire: "Africa/Abidjan",
  lesotho: "Africa/Maseru",
  liberia: "Africa/Monrovia",
  libya: "Africa/Tripoli",
  madagascar: "Indian/Antananarivo",
  malawi: "Africa/Blantyre",
  mali: "Africa/Bamako",
  mauritania: "Africa/Nouakchott",
  mauritius: "Indian/Mauritius",
  morocco: "Africa/Casablanca",
  mozambique: "Africa/Maputo",
  namibia: "Africa/Windhoek",
  niger: "Africa/Niamey",
  reunion: "Indian/Reunion",
  rwanda: "Africa/Kigali",
  sao_tome_and_principe: "Africa/Sao_Tome",
  senegal: "Africa/Dakar",
  seychelles: "Indian/Mahe",
  sierra_leone: "Africa/Freetown",
  somalia: "Africa/Mogadishu",
  sudan: "Africa/Khartoum",
  south_sudan: "Africa/Juba",
  tanzania: "Africa/Dar_es_Salaam",
  togo: "Africa/Lome",
  tunisia: "Africa/Tunis",
  uganda: "Africa/Kampala",
  zambia: "Africa/Lusaka",
  zimbabwe: "Africa/Harare",

  // --- AMERICAS (NORTH, CENTRAL, SOUTH, CARIBBEAN) ---
  anguilla: "America/Anguilla",
  antigua_and_barbuda: "America/Antigua",
  argentina: "America/Argentina/Buenos_Aires",
  aruba: "America/Aruba",
  bahamas: "America/Nassau",
  barbados: "America/Barbados",
  belize: "America/Belize",
  bermuda: "Atlantic/Bermuda",
  bolivia: "America/La_Paz",
  brazil: "America/Sao_Paulo",
  british_virgin_islands: "America/Tortola",
  cayman_islands: "America/Cayman",
  chile: "America/Santiago",
  colombia: "America/Bogota",
  costa_rica: "America/Costa_Rica",
  cuba: "America/Havana",
  curacao: "America/Curacao",
  dominica: "America/Dominica",
  dominican_republic: "America/Santo_Domingo",
  ecuador: "America/Guayaquil",
  el_salvador: "America/El_Salvador",
  greenland: "America/Nuuk",
  grenada: "America/Grenada",
  guadeloupe: "America/Marigot",
  guatemala: "America/Guatemala",
  guyana: "America/Guyana",
  haiti: "America/Port-au-Prince",
  honduras: "America/Tegucigalpa",
  jamaica: "America/Jamaica",
  martinique: "America/Martinique",
  mexico: "America/Mexico_City",
  montserrat: "America/Montserrat",
  nicaragua: "America/Managua",
  panama: "America/Panama",
  paraguay: "America/Asuncion",
  peru: "America/Lima",
  puerto_rico: "America/Puerto_Rico",
  saint_kitts_and_nevis: "America/St_Kitts",
  saint_lucia: "America/St_Lucia",
  saint_vincent: "America/St_Vincent",
  suriname: "America/Paramaribo",
  trinidad_and_tobago: "America/Port_of_Spain",
  turks_and_caicos: "America/Grand_Turk",
  uruguay: "America/Montevideo",
  venezuela: "America/Caracas",
  us_virgin_islands: "America/St_Thomas",

  // --- ASIA ---
  afghanistan: "Asia/Kabul",
  armenia: "Asia/Yerevan",
  azerbaijan: "Asia/Baku",
  bahrain: "Asia/Bahrain",
  bangladesh: "Asia/Dhaka",
  bhutan: "Asia/Thimphu",
  brunei: "Asia/Brunei",
  cambodia: "Asia/Phnom_Penh",
  georgia: "Asia/Tbilisi",
  hong_kong: "Asia/Hong_Kong",
  indonesia: "Asia/Jakarta",
  iran: "Asia/Tehran",
  iraq: "Asia/Baghdad",
  israel: "Asia/Jerusalem",
  jordan: "Asia/Amman",
  kazakhstan: "Asia/Almaty",
  kuwait: "Asia/Kuwait",
  kyrgyzstan: "Asia/Bishkek",
  laos: "Asia/Vientiane",
  lebanon: "Asia/Beirut",
  macau: "Asia/Macau",
  malaysia: "Asia/Kuala_Lumpur",
  maldives: "Indian/Maldives",
  mongolia: "Asia/Ulaanbaatar",
  myanmar: "Asia/Yangon",
  burma: "Asia/Yangon",
  nepal: "Asia/Kathmandu",
  north_korea: "Asia/Pyongyang",
  oman: "Asia/Muscat",
  pakistan: "Asia/Karachi",
  palestine: "Asia/Gaza",
  philippines: "Asia/Manila",
  qatar: "Asia/Qatar",
  saudi_arabia: "Asia/Riyadh",
  singapore: "Asia/Singapore",
  south_korea: "Asia/Seoul",
  sri_lanka: "Asia/Colombo",
  syria: "Asia/Damascus",
  taiwan: "Asia/Taipei",
  tajikistan: "Asia/Dushanbe",
  thailand: "Asia/Bangkok",
  timor_leste: "Asia/Dili",
  turkmenistan: "Asia/Ashgabat",
  uae: "Asia/Dubai",
  united_arab_emirates: "Asia/Dubai",
  uzbekistan: "Asia/Tashkent",
  vietnam: "Asia/Ho_Chi_Minh",
  yemen: "Asia/Aden",

  // --- EUROPE ---
  albania: "Europe/Tirane",
  andorra: "Europe/Andorra",
  austria: "Europe/Vienna",
  belarus: "Europe/Minsk",
  belgium: "Europe/Brussels",
  bosnia_and_herzegovina: "Europe/Sarajevo",
  bulgaria: "Europe/Sofia",
  croatia: "Europe/Zagreb",
  cyprus: "Asia/Nicosia",
  czech_republic: "Europe/Prague",
  czechia: "Europe/Prague",
  denmark: "Europe/Copenhagen",
  estonia: "Europe/Tallinn",
  finland: "Europe/Helsinki",
  france: "Europe/Paris",
  germany: "Europe/Berlin",
  gibraltar: "Europe/Gibraltar",
  greece: "Europe/Athens",
  hungary: "Europe/Budapest",
  iceland: "Atlantic/Reykjavik",
  ireland: "Europe/Dublin",
  italy: "Europe/Rome",
  latvia: "Europe/Riga",
  liechtenstein: "Europe/Vaduz",
  lithuania: "Europe/Vilnius",
  luxembourg: "Europe/Luxembourg",
  malta: "Europe/Malta",
  moldova: "Europe/Chisinau",
  monaco: "Europe/Monaco",
  montenegro: "Europe/Podgorica",
  netherlands: "Europe/Amsterdam",
  the_netherlands: "Europe/Amsterdam",
  north_macedonia: "Europe/Skopje",
  norway: "Europe/Oslo",
  poland: "Europe/Warsaw",
  portugal: "Europe/Lisbon",
  romania: "Europe/Bucharest",
  russia: "Europe/Moscow",
  san_marino: "Europe/San_Marino",
  serbia: "Europe/Belgrade",
  slovakia: "Europe/Bratislava",
  slovenia: "Europe/Ljubljana",
  spain: "Europe/Madrid",
  sweden: "Europe/Stockholm",
  switzerland: "Europe/Zurich",
  turkey: "Europe/Istanbul",
  ukraine: "Europe/Kyiv",
  vatican_city: "Europe/Vatican",

  // --- OCEANIA ---
  fiji: "Pacific/Fiji",
  french_polynesia: "Pacific/Tahiti",
  guam: "Pacific/Guam",
  kiribati: "Pacific/Tarawa",
  marshall_islands: "Pacific/Majuro",
  micronesia: "Pacific/Chuuk",
  nauru: "Pacific/Nauru",
  new_caledonia: "Pacific/Noumea",
  new_zealand: "Pacific/Auckland",
  palau: "Pacific/Palau",
  papua_new_guinea: "Pacific/Port_Moresby",
  samoa: "Pacific/Apia",
  solomon_islands: "Pacific/Guadalcanal",
  tonga: "Pacific/Tongatapu",
  tuvalu: "Pacific/Funafuti",
  vanuatu: "Pacific/Efate",

  // Ivory Coast Variants
  cote_d_ivoire: "Africa/Abidjan",
  çöte_divoire: "Africa/Abidjan", // Handles your typo variation cleanly

  // Turkey / Türkiye Variants
  turkiye: "Europe/Istanbul",
  türkiye: "Europe/Istanbul",
  republic_of_turkey: "Europe/Istanbul",
  republic_of_türkiye: "Europe/Istanbul",

  // --- UTC / FIXED REFERENCE ---
  utc: "UTC",
  gmt: "UTC",
};

export const weatherDetails = [
  {
    name: "real feel",
    value: "apparent_temperature",
    append: "°",
  },
  {
    name: "wind",
    value: "wind_direction_10m",
    append: "km/h",
  },
  {
    name: "pressure",
    value: "pressure_msl",
    append: "mb"
  },
  {
    name: "Humidity",
    value: "relative_humidity_2m",
    append: "%",
  },
];
